### ISSUE TITLE
Suggest a better db setup code

### ISSUE THREAD

**Issue by benjamin-thomas** [paurkedal/caqti-study#2]
Following the discussions at: https://github.com/paurkedal/caqti-study/pull/1, let's see if I can get rid of `connect` for a more idiomatic usage of Caqti.

**Comment by benjamin-thomas** [comment]
To encourage thinking in terms of connection values which we pass around, I'm thinking of changing the `hello-caqti-blocking/bin/main.ml` example like such:

```ocaml
(*
  Run with:

    PGHOST=localhost PGDATABASE=caqti_study PGPORT=5433 dune exec ./bin/main.exe
*)

open Printf

let add_with_db conn a b = Result.bind (Repo.Exec.add conn a b) (fun n -> Ok n)

let mul_with_db a b conn =
  let ( let* ) = Result.bind in
  let* n = Repo.Exec.mul conn a b in
  Ok n

let tag_err msg = Result.map_error (fun err -> (msg, err))

let do_work =
  let ( let* ) = Result.bind in
  let* conn = Repo.Init.connect () |> tag_err "could not connect" in
  let* n1 = add_with_db conn 1 2 |> tag_err "could not add" in
  let* n2 = mul_with_db 3 4 conn |> tag_err "could not multiply" in
  printf "1) DB says 1+2 = %d\n" n1;
  printf "2) DB says 3*4 = %d\n" n2;
  Result.ok ()

let () =
  match do_work with
  | Error (msg, caqti_err) ->
      prerr_endline msg;
      prerr_endline (Caqti_error.show caqti_err)
  | Ok () -> print_endline "Finished!"

```

We get a handle on the connection once, then we pass it around.

Does that sound good to you @paurkedal?

I still keep `Repo.Init.connect` because we have to put the code somewhere and we can play with in in the REPL that way.

I could put a documentation comment that the function should ideally be called once.

**Comment by paurkedal** [comment]
I think it's a decision for the application developer whether to connect where needed or use a single connection, but in a short-lived application like this, using a single connection makes most sense, and I think it's also a common case.  So, yes.

But I'm wondering, why the different position of the `conn` argument in the two functions?

**Comment by benjamin-thomas** [comment]
Oops, I shouldn't have auto-closed this, sorry for the noise.

Ok Petter, I'll use this little improvement then.

> But I'm wondering, why the different position of the conn argument in the two functions?

That wasn't intentional, I'll fix this thanks!

**Comment by paurkedal** [comment]
Yes, please keep the shared connect; I agree it's better, even if I was a vague about it.

**Comment by benjamin-thomas** [comment]
I think we're all good. I think I reopened thinking I had left an inconsistent order of arguments regarding `conn`.

But I do already pass it as a first parameter everywhere on the `main` branch.
