### ISSUE TITLE
Improve the dependencies management

### ISSUE THREAD

**Issue by benjamin-thomas** [paurkedal/caqti-study#8]
At the moment, I suggest running a bunch of `opam install` calls.

I'm thinking of adding an `dev.opam` file at the project root:

```
# dev.opam
(*

  To install the dependencies listed in this file, run:
    opam install . --deps-only

  ---

  To optionally isolate these dependencies to the current folder, create a "switch" like so:
    opam switch create . {OCAML_VERSION} --deps-only

  Or optionally install as a global switch with a custom name:
    opam switch create caqti-study 5.1.0

  ---

  Run this to find the latest OCaml version:
    opam switch list-available | grep -E 'base-compiler.+Official'

  ---

  To find your current switch configuration, run:
    opam switch

  ---

  Other useful commands:
    - opam switch       # find currently installed switches
    - opam switch 5.1.0 # change to the 5.10 switch configuration

*)

opam-version: "2.0"

depends: [
  "caqti" { >= "2.0.1" }

  "caqti-driver-postgresql"
  "caqti-lwt"
  "caqti-async"
  "ppx_rapper"

  # Below is for testing only
  "base"
  "ppx_assert"
  "ppx_inline_test"

  # Below is for documentation purposes
  "mdx"
]
```

And update the README to suggest calling instead:

```
opam install . --deps-only
```

This generates warnings about missing mandatory opam fields, but that seem ok to ignore.

Opam's dependency resolution seems to work fine specifying only `caqti`'s specific version.

**Comment by paurkedal** [comment]
I'm not sure what's the best approach here, since it's not meant to be an installable package.  The most simple alternative might be to just merge all `opam install` line into one, since multiple arguments are allowed.  Since there is already a `Makefile` maybe a `make` target would be more elegant?  I'm not against the opam approach either, though.

**Comment by benjamin-thomas** [comment]
Hello Petter,

For info, I added this dev.opam file in the end, since I experienced a switch getting "out of sync" a few days ago and it was just a bit of unnecessary friction trying to get back into a working state.

So since it doesn't hurt, I pushed it.

**Comment by paurkedal** [comment]
I can see you're using the opportunity to teach OCaml tooling in the comment, good idea.  Some possibly improvement in that direction might be to use the `{with-test}` and `{with-doc}` flags and add corresponding `-t`/`--with-test` and `-d`/`--with-doc` options.

**Comment by benjamin-thomas** [comment]
> I can see you're using the opportunity to teach OCaml tooling in the comment, good idea. Some possibly improvement in that direction might be to use the `{with-test}` and `{with-doc}` flags and add corresponding `-t`/`--with-test` and `-d`/`--with-doc` options.

Thanks I'll look into that!
